version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: "@grpc/proto-loader"
    versions:
    - 0.5.6
    - 0.6.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: apollo-server-express
    versions:
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.0
    - 2.22.1
    - 2.22.2
  - dependency-name: knex
    versions:
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: "@grpc/grpc-js"
    versions:
    - 1.2.10
    - 1.2.11
    - 1.2.12
    - 1.2.5
    - 1.2.6
    - 1.2.7
    - 1.2.8
    - 1.2.9
  - dependency-name: socket.io
    versions:
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: semantic-release
    versions:
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: amqplib
    versions:
    - 0.7.0
